### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by joseluis** [theduke/crates_io_api#10]
Fixing a couple of bugs (probably because the crates.io API was recently updated), I realized the need of testing to make sure a fix doesn't break other things.

Edit: I think I may want to add some tests and make this into a PR

**Comment by joseluis** [comment]
I was thinking on having some tests to detect API changes in order to automatically check the received structures against the defined types. I think that would be useful for maintenance purposes.

**Comment by theduke** [comment]
We can add `#[serde(deny_unknown_fields)]` to the structs to fail when new unknown fields are added.
If fields are missing or change type, the tests would fail anyway.
