### ISSUE TITLE
The client is not Send

### ISSUE THREAD

**Issue by kornelski** [theduke/crates_io_api#21]
Internal use of RefCell instead of Mutex makes it unsafe to use across threads, which is limiting for multithreaded programs.

I've had to duplicate the client for each thread, but I assume it breaks rate-limiting.

**Comment by theduke** [comment]
The async client does use a mutex.

I had sort of assumed that the sync client would only be used from a single thread, since you would easily bump against the rate limit anyway.

Sharing/moving the client is an argument of course. 

Happy to use a mutex in the sync client as well.

**Comment by theduke** [comment]
Released as `0.6.1`.
