### ISSUE TITLE
adding support for third-party repos would be neat

### ISSUE THREAD

**Issue by przygienda** [theduke/crates_io_api#6]

**Comment by theduke** [comment]
Do you mean a custom registry?

So all that would need to be customized is the root API url?

**Comment by przygienda** [comment]
I'm in the process of re-writing crates.io code to support a custom registry. quite significant amount of work actually ... I'll probably drop a summary what all needed to be done when finished ...

**Comment by theduke** [comment]
@przygienda great, let me know when something becomes actionable.

**Comment by theduke** [comment]
Closing this. Feel free to reopen once something is actionable.
